// ninja/gen.go - Ninja file generator
package ninja

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"minibp/parser"
)

// Graph is the interface needed for ninja generation
type Graph interface {
	TopoSort() ([][]string, error)
}

// Generator creates ninja build files from module dependency graphs
type Generator struct {
	graph      Graph
	rules      map[string]BuildRule
	modules    map[string]*parser.Module
	sourceDir  string
	outputDir  string
	pathPrefix string
	regenCmd   string
	inputFiles []string
	outputFile string
	workDir    string
	toolchain  Toolchain
	arch       string
}

// Toolchain holds compiler/tool configuration for cross-compilation
type Toolchain struct {
	CC      string   // C compiler (default: gcc)
	CXX     string   // C++ compiler (default: g++)
	AR      string   // archiver (default: ar)
	CFlags  []string // extra global cflags
	LdFlags []string // extra global ldflags
}

// NewGenerator creates a new Generator with the given graph and rules
func NewGenerator(g Graph, rules map[string]BuildRule, modules map[string]*parser.Module) *Generator {
	return &Generator{
		graph:     g,
		rules:     rules,
		modules:   modules,
		sourceDir: ".",
		outputDir: ".",
	}
}

// SetSourceDir sets the source directory (where .bp files are)
func (g *Generator) SetSourceDir(dir string) {
	g.sourceDir = dir
}

// SetOutputDir sets the output directory (where ninja will run)
func (g *Generator) SetOutputDir(dir string) {
	g.outputDir = dir
}

// SetPathPrefix sets the prefix to prepend to source file paths
func (g *Generator) SetPathPrefix(prefix string) {
	g.pathPrefix = prefix
}

// SetRegen sets the command and files for auto-regeneration of build.ninja
func (g *Generator) SetRegen(cmd string, files []string, output string) {
	g.regenCmd = cmd
	g.inputFiles = files
	g.outputFile = output
}

func (g *Generator) SetWorkDir(dir string) {
	g.workDir = dir
}

func (g *Generator) SetToolchain(t Toolchain) {
	g.toolchain = t
}

func (g *Generator) SetArch(arch string) {
	g.arch = arch
}

func DefaultToolchain() Toolchain {
	return Toolchain{
		CC:  "gcc",
		CXX: "g++",
		AR:  "ar",
	}
}

// getRelativePath returns the path from outputDir to a file in sourceDir
func (g *Generator) getRelativePath(file string) string {
	if g.sourceDir == g.outputDir {
		return file
	}
	absSource, _ := filepath.Abs(g.sourceDir)
	absOutput, _ := filepath.Abs(g.outputDir)
	if rel, err := filepath.Rel(absOutput, absSource); err == nil {
		if rel == "." {
			return file
		}
		return filepath.Join(rel, file)
	}
	return file
}

// collectIncludePaths recursively collects export_include_dirs from dependencies
func (g *Generator) collectIncludePaths(moduleName string, visited map[string]bool) []string {
	if visited[moduleName] {
		return nil
	}
	visited[moduleName] = true

	m, ok := g.modules[moduleName]
	if !ok || m == nil {
		return nil
	}

	var includes []string
	seen := make(map[string]bool)

	// Check if this is a cc_library_headers module
	if m.Type == "cc_library_headers" {
		dirs := getExportIncludeDirs(m)
		for _, dir := range dirs {
			if !seen[dir] {
				includes = append(includes, dir)
				seen[dir] = true
			}
		}
	}

	// Get direct export_include_dirs
	dirs := getExportIncludeDirs(m)
	for _, dir := range dirs {
		if !seen[dir] {
			includes = append(includes, dir)
			seen[dir] = true
		}
	}

	// Collect directories from exported_headers (individual .h files)
	exportedHeaders := getExportedHeaders(m)
	for _, h := range exportedHeaders {
		dir := filepath.Dir(h)
		if dir != "" && dir != "." && !seen[dir] {
			includes = append(includes, dir)
			seen[dir] = true
		}
	}

	// Collect from header_libs (cc_library_headers dependencies)
	headerLibs := GetListProp(m, "header_libs")
	for _, dep := range headerLibs {
		depName := strings.TrimPrefix(dep, ":")
		depIncludes := g.collectIncludePaths(depName, visited)
		for _, dir := range depIncludes {
			if !seen[dir] {
				includes = append(includes, dir)
				seen[dir] = true
			}
		}
	}

	// Recursively collect from deps (option B: transitive)
	deps := GetListProp(m, "deps")
	for _, dep := range deps {
		depName := strings.TrimPrefix(dep, ":")
		depIncludes := g.collectIncludePaths(depName, visited)
		for _, dir := range depIncludes {
			if !seen[dir] {
				includes = append(includes, dir)
				seen[dir] = true
			}
		}
	}

	return includes
}

// Generate writes the ninja build file content to the provided writer
func (g *Generator) Generate(w io.Writer) error {
	nw := NewWriter(w)

	nw.Comment("Generated by minibp")
	nw.Comment("")

	if g.regenCmd != "" && len(g.inputFiles) > 0 {
		fmt.Fprintf(w, "rule regen\n command = %s\n\n", g.regenCmd)
		fmt.Fprintf(w, "build %s: regen %s\n\n", g.outputFile, strings.Join(g.inputFiles, " "))
	}

	if g.outputDir != "." && g.outputDir != "" {
		nw.Variable("builddir", ".")
		nw.Comment("")
	}

	// Set toolchain env vars before generating rules (rules read them via getCC/getCXX/getAR)
	tc := g.toolchain
	if tc.CC == "" {
		tc.CC = "gcc"
	}
	if tc.CXX == "" {
		tc.CXX = "g++"
	}
	if tc.AR == "" {
		tc.AR = "ar"
	}
	os.Setenv("MINIBP_CC", tc.CC)
	os.Setenv("MINIBP_CXX", tc.CXX)
	os.Setenv("MINIBP_AR", tc.AR)
	archSuffix := ""
	if g.arch != "" {
		os.Setenv("MINIBP_ARCH", g.arch)
		archSuffix = "_" + g.arch
	}
	os.Setenv("MINIBP_ARCH_SUFFIX", archSuffix)

	usedModuleTypes := g.collectUsedModuleTypes()

	writtenNinjaRules := make(map[string]bool)

	for _, moduleType := range usedModuleTypes {
		if rule, ok := g.rules[moduleType]; ok {
			ruleDef := rule.NinjaRule()
			if ruleDef == "" {
				continue
			}
			parts := strings.Split(ruleDef, "rule ")
			for i, part := range parts {
				if i == 0 && part == "" {
					continue
				}
				if part == "" {
					continue
				}
				lines := strings.SplitN(part, "\n", 2)
				ninjaRuleName := strings.TrimSpace(lines[0])
				if ninjaRuleName != "" && !writtenNinjaRules[ninjaRuleName] {
					writtenNinjaRules[ninjaRuleName] = true
					fmt.Fprintf(w, "rule %s", part)
				}
			}
		}
	}

	levels, err := g.graph.TopoSort()
	if err != nil {
		return err
	}

	os.Setenv("MINIBP_SOURCE_PREFIX", g.getRelativePath(""))

	var allOutputs []string

	for _, level := range levels {
		for _, moduleName := range level {
			m, ok := g.modules[moduleName]
			if !ok || m == nil {
				continue
			}

			rule, ok := g.rules[m.Type]
			if !ok {
				continue
			}

			visited := make(map[string]bool)
			includes := g.collectIncludePaths(moduleName, visited)

			if strings.HasPrefix(m.Type, "cc_") || strings.HasPrefix(m.Type, "cpp_") {
				seen := make(map[string]bool)
				for _, inc := range includes {
					seen[inc] = true
				}
				if !seen["."] {
					includes = append(includes, ".")
				}
				srcs := getSrcs(m)
				for _, src := range srcs {
					dir := filepath.Dir(src)
					if dir != "." && !seen[dir] {
						includes = append(includes, dir)
						seen[dir] = true
					}
				}
			}

			sourceDir := g.sourceDir
			if sourceDir == "." {
				absPath, _ := filepath.Abs(g.sourceDir)
				sourceDir = filepath.Base(absPath)
			}

			edgeDef := rule.NinjaEdge(m)
			if m.Type == "custom" {
				edgeDef = customRuleEdge(m, g.workDir)
			}
			if edgeDef == "" && m.Type != "cc_library_headers" {
				continue
			}

			if edgeDef != "" {
				edgeDef = g.addIncludesToEdge(edgeDef, includes)
			}

			if outputs := rule.Outputs(m); len(outputs) > 0 {
				allOutputs = append(allOutputs, outputs...)
			}

			srcs := getSrcs(m)
			if len(srcs) == 0 {
				desc := rule.Desc(m, "")
				if desc != "" {
					nw.Desc(sourceDir, moduleName, desc, "")
				}
			} else {
				for _, src := range srcs {
					desc := rule.Desc(m, src)
					if desc != "" {
						nw.Desc(sourceDir, moduleName, desc, src)
					}
				}
			}

			fmt.Fprint(w, g.adjustPaths(edgeDef))
		}
	}

	if len(allOutputs) > 0 {
		fmt.Fprintf(w, "\nrule clean\n command = rm -f %s\n", strings.Join(allOutputs, " "))
		fmt.Fprintf(w, "\nbuild clean: clean\n")
	}

	if len(allOutputs) > 0 {
		fmt.Fprintln(w)
		for _, out := range allOutputs {
			fmt.Fprintf(w, "build %s: phony\n", out)
		}
	}

	return nil
}

// addIncludesToEdge adds include directories to compile commands
func (g *Generator) addIncludesToEdge(edge string, includes []string) string {
	if len(includes) == 0 {
		return edge
	}

	includeFlags := ""
	relPrefix := g.getRelativePath("")
	for _, inc := range includes {
		if relPrefix != "" && relPrefix != "." {
			inc = filepath.Join(relPrefix, inc)
		}
		includeFlags += " -I" + inc
	}

	// Add to flags variable in edge
	lines := strings.Split(edge, "\n")
	for i, line := range lines {
		if strings.Contains(line, "flags =") && !strings.Contains(line, "#") {
			// Append includes to existing flags
			lines[i] = line + includeFlags
		}
	}

	return strings.Join(lines, "\n")
}

// adjustPaths updates paths in ninja edge to be relative to output directory
func (g *Generator) adjustPaths(edge string) string {
	if g.pathPrefix == "" {
		return edge
	}

	lines := strings.Split(edge, "\n")
	var adjustedLines []string

	for _, line := range lines {
		if !strings.HasPrefix(line, "build ") {
			adjustedLines = append(adjustedLines, line)
			continue
		}

		re := strings.SplitN(line, ": ", 2)
		if len(re) < 2 {
			adjustedLines = append(adjustedLines, line)
			continue
		}

		colonPart := re[0] + ": "
		ruleAndInputs := re[1]

		fields := strings.Fields(ruleAndInputs)
		if len(fields) < 2 {
			adjustedLines = append(adjustedLines, line)
			continue
		}

		inputs := fields[1:]
		for i, input := range inputs {
			if input == "|" {
				continue
			}
			if !strings.HasPrefix(input, "$") &&
				!strings.HasPrefix(input, g.pathPrefix) &&
				!strings.HasPrefix(input, "/") &&
				!strings.HasPrefix(input, "..") &&
				!strings.HasSuffix(input, ".o") &&
				!strings.HasSuffix(input, ".a") &&
				!strings.HasSuffix(input, ".so") &&
				!strings.HasSuffix(input, ".stamp") {
				inputs[i] = g.pathPrefix + input
			}
		}

		adjustedLines = append(adjustedLines, colonPart+fields[0]+" "+strings.Join(inputs, " "))
	}

	return strings.Join(adjustedLines, "\n")
}

// collectUsedModuleTypes returns a deduplicated list of module types used
func (g *Generator) collectUsedModuleTypes() []string {
	seen := make(map[string]bool)
	var result []string

	for _, m := range g.modules {
		if m == nil {
			continue
		}
		if !seen[m.Type] {
			seen[m.Type] = true
			result = append(result, m.Type)
		}
	}

	return result
}

// collectRulesForModule returns all ninja rule names used by a build rule
func (g *Generator) collectRulesForModule(rule BuildRule) []string {
	// Extract rule names from NinjaRule() output
	ruleDef := rule.NinjaRule()
	var rules []string
	seen := make(map[string]bool)

	lines := strings.Split(ruleDef, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "rule ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				name := parts[1]
				if !seen[name] {
					seen[name] = true
					rules = append(rules, name)
				}
			}
		}
	}

	return rules
}
