// ninja/gen.go - Ninja file generator
package ninja

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"minibp/parser"
)

// Graph is the interface needed for ninja generation
type Graph interface {
	TopoSort() ([][]string, error)
}

// Generator creates ninja build files from module dependency graphs
type Generator struct {
	graph      Graph
	rules      map[string]BuildRule
	modules    map[string]*parser.Module
	sourceDir  string
	outputDir  string
	pathPrefix string
}

// NewGenerator creates a new Generator with the given graph and rules
func NewGenerator(g Graph, rules map[string]BuildRule, modules map[string]*parser.Module) *Generator {
	return &Generator{
		graph:     g,
		rules:     rules,
		modules:   modules,
		sourceDir: ".",
		outputDir: ".",
	}
}

// SetSourceDir sets the source directory (where .bp files are)
func (g *Generator) SetSourceDir(dir string) {
	g.sourceDir = dir
}

// SetOutputDir sets the output directory (where ninja will run)
func (g *Generator) SetOutputDir(dir string) {
	g.outputDir = dir
}

// SetPathPrefix sets the prefix to prepend to source file paths
func (g *Generator) SetPathPrefix(prefix string) {
	g.pathPrefix = prefix
}

// getRelativePath returns the path from outputDir to a file in sourceDir
func (g *Generator) getRelativePath(file string) string {
	if g.sourceDir == g.outputDir {
		return file
	}
	absSource, _ := filepath.Abs(g.sourceDir)
	absOutput, _ := filepath.Abs(g.outputDir)
	if rel, err := filepath.Rel(absOutput, absSource); err == nil {
		if rel == "." {
			return file
		}
		return filepath.Join(rel, file)
	}
	return file
}

// collectIncludePaths recursively collects export_include_dirs from dependencies
func (g *Generator) collectIncludePaths(moduleName string, visited map[string]bool) []string {
	if visited[moduleName] {
		return nil
	}
	visited[moduleName] = true

	m, ok := g.modules[moduleName]
	if !ok || m == nil {
		return nil
	}

	var includes []string
	seen := make(map[string]bool)

	// Get direct export_include_dirs
	dirs := getExportIncludeDirs(m)
	for _, dir := range dirs {
		if !seen[dir] {
			includes = append(includes, dir)
			seen[dir] = true
		}
	}

	// Recursively collect from dependencies (option B: transitive)
	deps := getListProp(m, "deps")
	for _, dep := range deps {
		depName := strings.TrimPrefix(dep, ":")
		depIncludes := g.collectIncludePaths(depName, visited)
		for _, dir := range depIncludes {
			if !seen[dir] {
				includes = append(includes, dir)
				seen[dir] = true
			}
		}
	}

	return includes
}

// Generate writes the ninja build file content to the provided writer
func (g *Generator) Generate(w io.Writer) error {
	nw := NewWriter(w)

	// Write header comment
	nw.Comment("Generated by minibp")
	nw.Comment("")

	// Write builddir declaration if output dir is different
	if g.outputDir != "." && g.outputDir != "" {
		nw.Variable("builddir", ".")
		nw.Comment("")
	}

	// Collect used module types
	usedModuleTypes := g.collectUsedModuleTypes()

	// Use a map to track which ninja rules have been written to avoid duplicates
	writtenNinjaRules := make(map[string]bool)

	// Write rule definitions for all used module types
	for _, moduleType := range usedModuleTypes {
		if rule, ok := g.rules[moduleType]; ok {
			ruleDef := rule.NinjaRule()
			if ruleDef == "" {
				continue
			}
			// Split by "rule " to handle multiple rule definitions
			parts := strings.Split(ruleDef, "rule ")
			for i, part := range parts {
				if i == 0 && part == "" {
					continue // Skip empty first part
				}
				if part == "" {
					continue
				}
				// Extract rule name (first word)
				lines := strings.SplitN(part, "\n", 2)
				ninjaRuleName := strings.TrimSpace(lines[0])
				if ninjaRuleName != "" && !writtenNinjaRules[ninjaRuleName] {
					writtenNinjaRules[ninjaRuleName] = true
					fmt.Fprintf(w, "rule %s", part)
				}
			}
		}
	}

	// Get modules in topological order
	levels, err := g.graph.TopoSort()
	if err != nil {
		return err
	}

	// Set environment variable to signal path adjustment
	os.Setenv("MINIBP_SOURCE_PREFIX", g.getRelativePath(""))

	// For each module, write build edge with desc
	for _, level := range levels {
		for _, moduleName := range level {
			m, ok := g.modules[moduleName]
			if !ok || m == nil {
				continue
			}

			rule, ok := g.rules[m.Type]
			if !ok {
				continue
			}

			// Collect include paths for this module
			visited := make(map[string]bool)
			includes := g.collectIncludePaths(moduleName, visited)

			// Get source directory for desc
			sourceDir := g.sourceDir
			if sourceDir == "." {
				absPath, _ := filepath.Abs(g.sourceDir)
				sourceDir = filepath.Base(absPath)
			}

			// Get module edge output
			edgeDef := rule.NinjaEdge(m)
			if edgeDef == "" {
				continue
			}

			// Add includes to edge if needed
			edgeDef = g.addIncludesToEdge(edgeDef, includes)

			// Parse edge to extract source files for desc
			srcs := getSrcs(m)
			if len(srcs) == 0 {
				// No source files, write single desc
				desc := rule.Desc(m, "")
				if desc != "" {
					nw.Desc(sourceDir, moduleName, desc, "")
				}
			} else {
				// Write desc for each source file
				for _, src := range srcs {
					desc := rule.Desc(m, src)
					if desc != "" {
						nw.Desc(sourceDir, moduleName, desc, src)
					}
				}
			}

			// Write build edge with adjusted paths
			fmt.Fprint(w, g.adjustPaths(edgeDef))
		}
	}

	return nil
}

// addIncludesToEdge adds include directories to compile commands
func (g *Generator) addIncludesToEdge(edge string, includes []string) string {
	if len(includes) == 0 {
		return edge
	}

	includeFlags := ""
	for _, inc := range includes {
		includeFlags += " -I" + inc
	}

	// Add to flags variable in edge
	lines := strings.Split(edge, "\n")
	for i, line := range lines {
		if strings.Contains(line, "flags =") && !strings.Contains(line, "#") {
			// Append includes to existing flags
			lines[i] = line + includeFlags
		}
	}

	return strings.Join(lines, "\n")
}

// adjustPaths updates paths in ninja edge to be relative to output directory
func (g *Generator) adjustPaths(edge string) string {
	if g.pathPrefix == "" {
		return edge
	}

	if !strings.HasPrefix(edge, "build ") {
		return edge
	}

	parts := strings.SplitN(edge, "\n", 2)
	buildLine := parts[0]
	rest := ""
	if len(parts) > 1 {
		rest = parts[1]
	}

	re := strings.SplitN(buildLine, ": ", 2)
	if len(re) < 2 {
		return edge
	}

	colonPart := re[0] + ": "
	ruleAndInputs := re[1]

	fields := strings.Fields(ruleAndInputs)
	if len(fields) < 2 {
		return edge
	}

	inputs := fields[1:]
	for i, input := range inputs {
		// Skip variables and paths that already have the prefix or are absolute
		if !strings.HasPrefix(input, "$") &&
			!strings.HasPrefix(input, g.pathPrefix) &&
			!strings.HasPrefix(input, "/") &&
			!strings.HasPrefix(input, "..") {
			inputs[i] = g.pathPrefix + input
		}
	}

	return colonPart + fields[0] + " " + strings.Join(inputs, " ") + "\n" + rest
}

// collectUsedModuleTypes returns a deduplicated list of module types used
func (g *Generator) collectUsedModuleTypes() []string {
	seen := make(map[string]bool)
	var result []string

	for _, m := range g.modules {
		if m == nil {
			continue
		}
		if !seen[m.Type] {
			seen[m.Type] = true
			result = append(result, m.Type)
		}
	}

	return result
}

// collectRulesForModule returns all ninja rule names used by a build rule
func (g *Generator) collectRulesForModule(rule BuildRule) []string {
	// Extract rule names from NinjaRule() output
	ruleDef := rule.NinjaRule()
	var rules []string
	seen := make(map[string]bool)

	lines := strings.Split(ruleDef, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "rule ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				name := parts[1]
				if !seen[name] {
					seen[name] = true
					rules = append(rules, name)
				}
			}
		}
	}

	return rules
}
