// ninja/gen.go - Ninja file generator
package ninja

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"minibp/parser"
)

// Graph is the interface needed for ninja generation
type Graph interface {
	TopoSort() ([][]string, error)
}

// Generator creates ninja build files from module dependency graphs
type Generator struct {
	graph      Graph
	rules      map[string]BuildRule
	modules    map[string]*parser.Module
	sourceDir  string
	outputDir  string
	pathPrefix string
}

// NewGenerator creates a new Generator with the given graph and rules
func NewGenerator(g Graph, rules map[string]BuildRule, modules map[string]*parser.Module) *Generator {
	return &Generator{
		graph:     g,
		rules:     rules,
		modules:   modules,
		sourceDir: ".",
		outputDir: ".",
	}
}

// SetSourceDir sets the source directory (where .bp files are)
func (g *Generator) SetSourceDir(dir string) {
	g.sourceDir = dir
}

// SetOutputDir sets the output directory (where ninja will run)
func (g *Generator) SetOutputDir(dir string) {
	g.outputDir = dir
}

// SetPathPrefix sets the prefix to prepend to source file paths
func (g *Generator) SetPathPrefix(prefix string) {
	g.pathPrefix = prefix
}

// getRelativePath returns the path from outputDir to a file in sourceDir
func (g *Generator) getRelativePath(file string) string {
	// If source and output are the same, return file as-is
	if g.sourceDir == g.outputDir {
		return file
	}

	// Make paths absolute for reliable comparison
	absSource, _ := filepath.Abs(g.sourceDir)
	absOutput, _ := filepath.Abs(g.outputDir)

	// If output is inside source, calculate relative path
	if rel, err := filepath.Rel(absOutput, absSource); err == nil {
		if rel == "." {
			return file
		}
		return filepath.Join(rel, file)
	}

	return file
}

// Generate writes the ninja build file content to the provided writer
func (g *Generator) Generate(w io.Writer) error {
	nw := NewWriter(w)

	// Write header comment
	nw.Comment("Generated by minibp")
	nw.Comment("")

	// Write builddir declaration if output dir is different
	if g.outputDir != "." && g.outputDir != "" {
		nw.Variable("builddir", ".")
		nw.Comment("")
	}

	// Collect used rules and write their definitions
	usedRules := g.collectUsedRules()
	for _, ruleName := range usedRules {
		if rule, ok := g.rules[ruleName]; ok {
			ruleDef := rule.NinjaRule()
			fmt.Fprint(w, ruleDef)
		}
	}

	// Get modules in topological order
	levels, err := g.graph.TopoSort()
	if err != nil {
		return err
	}

	// Set environment variable to signal path adjustment
	os.Setenv("MINIBP_SOURCE_PREFIX", g.getRelativePath(""))

	// For each module, write build edge
	for _, level := range levels {
		for _, moduleName := range level {
			m, ok := g.modules[moduleName]
			if !ok || m == nil {
				continue
			}

			rule, ok := g.rules[m.Type]
			if !ok {
				continue
			}

			// Write build edge with adjusted paths
			edgeDef := g.adjustPaths(rule.NinjaEdge(m))
			if edgeDef != "" {
				fmt.Fprint(w, edgeDef)
			}
		}
	}

	return nil
}

// adjustPaths updates paths in ninja edge to be relative to output directory
func (g *Generator) adjustPaths(edge string) string {
	if g.pathPrefix == "" {
		return edge
	}

	// Simple string replacement to prepend prefix to file paths
	// Format in ninja: "build output: rule input1 input2"
	// We need to prepend prefix to input files
	// Parse line: "build libdag.a: go_build_archive dag/graph.go"
	// Extract file paths after the rule name

	if !strings.HasPrefix(edge, "build ") {
		return edge
	}

	// Split into parts
	parts := strings.SplitN(edge, "\n", 2)
	buildLine := parts[0]
	rest := ""
	if len(parts) > 1 {
		rest = parts[1]
	}

	// Find where rule name ends and inputs start
	// Format: "build output: rule input1 input2"
	re := strings.SplitN(buildLine, ": ", 2)
	if len(re) < 2 {
		return edge
	}

	// re[0] = "build libdag.a"
	// re[1] = "go_build_archive dag/graph.go"
	colonPart := re[0] + ": "
	ruleAndInputs := re[1]

	// Split rule name from inputs
	fields := strings.Fields(ruleAndInputs)
	if len(fields) < 2 {
		return edge
	}

	ruleName := fields[0]
	inputs := fields[1:]

	// Prepend prefix to inputs (skip variables starting with $)
	for i, input := range inputs {
		if !strings.HasPrefix(input, "$") {
			inputs[i] = g.pathPrefix + input
		}
	}

	return colonPart + ruleName + " " + strings.Join(inputs, " ") + "\n" + rest
}

// collectUsedRules returns a deduplicated list of rule names used by modules
func (g *Generator) collectUsedRules() []string {
	seen := make(map[string]bool)
	var result []string

	for _, m := range g.modules {
		if m == nil {
			continue
		}
		if !seen[m.Type] {
			seen[m.Type] = true
			result = append(result, m.Type)
		}
	}

	return result
}
