// ninja/ninja_test.go - Tests for ninja package
package ninja

import (
	"bytes"
	"runtime"
	"strings"
	"testing"

	"minibp/dag"
	"minibp/parser"
)

type dagMockModule struct {
	name string
}

func (m *dagMockModule) Name() string                   { return m.name }
func (m *dagMockModule) Type() string                   { return "mock" }
func (m *dagMockModule) Srcs() []string                 { return nil }
func (m *dagMockModule) Deps() []string                 { return nil }
func (m *dagMockModule) Props() map[string]interface{}  { return nil }
func (m *dagMockModule) GetProp(key string) interface{} { return nil }

// mockRule implements BuildRule for testing
type mockRule struct {
	name string
}

func (r *mockRule) Name() string {
	return r.name
}

func (r *mockRule) NinjaRule() string {
	return "rule " + r.name + "\n  command = echo " + r.name + "\n"
}

func (r *mockRule) NinjaEdge(m *parser.Module) string {
	if m == nil {
		return ""
	}
	return "build " + getName(m) + ": " + r.name + " " + formatSrcs(getSrcs(m)) + "\n"
}

func (r *mockRule) Outputs(m *parser.Module) []string {
	return []string{getName(m)}
}

func (r *mockRule) Desc(m *parser.Module, srcFile string) string {
	return "mock"
}

func TestNewWriter(t *testing.T) {
	var buf bytes.Buffer
	w := NewWriter(&buf)
	if w == nil {
		t.Fatal("NewWriter returned nil")
	}
}

func TestWriterComment(t *testing.T) {
	var buf bytes.Buffer
	w := NewWriter(&buf)
	w.Comment("Test comment")
	output := buf.String()
	if !strings.Contains(output, "# Test comment") {
		t.Errorf("Expected comment in output, got: %s", output)
	}
}

func TestWriterVariable(t *testing.T) {
	var buf bytes.Buffer
	w := NewWriter(&buf)
	w.Variable("key", "value")
	output := buf.String()
	if !strings.Contains(output, "key = value") {
		t.Errorf("Expected variable in output, got: %s", output)
	}
}

func TestWriterRule(t *testing.T) {
	var buf bytes.Buffer
	w := NewWriter(&buf)
	w.Rule("cc", "gcc -c $in -o $out")
	output := buf.String()
	if !strings.Contains(output, "rule cc") {
		t.Errorf("Expected rule cc in output, got: %s", output)
	}
	if !strings.Contains(output, "command = gcc") {
		t.Errorf("Expected command in output, got: %s", output)
	}
}

func TestWriterBuild(t *testing.T) {
	var buf bytes.Buffer
	w := NewWriter(&buf)
	w.Build("out.o", "cc", []string{"in.c"}, nil)
	output := buf.String()
	if !strings.Contains(output, "build out.o: cc in.c") {
		t.Errorf("Expected build edge in output, got: %s", output)
	}
}

func TestWriterEscapesSpecialCharacters(t *testing.T) {
	var buf bytes.Buffer
	w := NewWriter(&buf)
	w.Build("out dir/file:name", "cc", []string{"src dir/$in.c"}, nil)
	output := buf.String()
	if !strings.Contains(output, "out$ dir/file$:name") {
		t.Fatalf("Expected escaped output path, got: %s", output)
	}
	if !strings.Contains(output, "src$ dir/$$in.c") {
		t.Fatalf("Expected escaped input path, got: %s", output)
	}
}

func TestCleanCommandQuotesOutputs(t *testing.T) {
	cmd := cleanCommand([]string{"out dir/app", "lib$name.a"})
	if runtime.GOOS == "windows" {
		if !strings.Contains(cmd, "cmd /c del /q") {
			t.Fatalf("Expected windows clean command, got: %s", cmd)
		}
	} else {
		if !strings.Contains(cmd, "rm -f") {
			t.Fatalf("Expected unix clean command, got: %s", cmd)
		}
	}
	if !strings.Contains(cmd, "\"out dir/app\"") || !strings.Contains(cmd, "\"lib$name.a\"") {
		t.Fatalf("Expected quoted outputs in clean command, got: %s", cmd)
	}
}

func TestJavaImportRuleUsesPlatformCopyCommand(t *testing.T) {
	r := &javaImport{}
	rule := r.NinjaRule()
	if runtime.GOOS == "windows" {
		if !strings.Contains(rule, "cmd /c copy") {
			t.Fatalf("Expected windows copy command, got: %s", rule)
		}
	} else {
		if !strings.Contains(rule, "cp $in $out") {
			t.Fatalf("Expected unix copy command, got: %s", rule)
		}
	}
}

func TestNewGenerator(t *testing.T) {
	g := dag.NewGraph()
	rules := make(map[string]BuildRule)
	modules := make(map[string]*parser.Module)
	gen := NewGenerator(g, rules, modules)
	if gen == nil {
		t.Fatal("NewGenerator returned nil")
	}
}

func TestGeneratorGenerate(t *testing.T) {
	g := dag.NewGraph()

	// Create a mock module
	m := &parser.Module{
		Type: "mock",
		Map: &parser.Map{
			Properties: []*parser.Property{
				{Name: "name", Value: &parser.String{Value: "hello"}},
				{Name: "srcs", Value: &parser.List{Values: []parser.Expression{
					&parser.String{Value: "main.c"},
				}}},
			},
		},
	}

	// Setup rules
	rules := map[string]BuildRule{
		"mock": &mockRule{name: "mock"},
	}

	// Setup modules
	modules := map[string]*parser.Module{
		"hello": m,
	}

	gen := NewGenerator(g, rules, modules)

	var buf bytes.Buffer
	err := gen.Generate(&buf)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	output := buf.String()

	// Check header
	if !strings.Contains(output, "Generated by minibp") {
		t.Errorf("Expected header in output, got: %s", output)
	}

	// Check rule definition
	if !strings.Contains(output, "rule mock") {
		t.Errorf("Expected rule definition in output, got: %s", output)
	}
}

func TestGeneratorWithCCLibrary(t *testing.T) {
	g := dag.NewGraph()

	m := &parser.Module{
		Type: "cc_library",
		Map: &parser.Map{
			Properties: []*parser.Property{
				{Name: "name", Value: &parser.String{Value: "mylib"}},
				{Name: "srcs", Value: &parser.List{Values: []parser.Expression{
					&parser.String{Value: "lib.c"},
				}}},
			},
		},
	}

	rules := map[string]BuildRule{
		"cc_library": &ccLibrary{},
	}

	modules := map[string]*parser.Module{
		"mylib": m,
	}

	gen := NewGenerator(g, rules, modules)

	var buf bytes.Buffer
	err := gen.Generate(&buf)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	output := buf.String()

	if !strings.Contains(output, "rule cc_compile") {
		t.Errorf("Expected cc_compile rule in output, got: %s", output)
	}

	if !strings.Contains(output, "rule cc_archive") {
		t.Errorf("Expected cc_archive rule in output, got: %s", output)
	}

	if !strings.Contains(output, "depfile = $out.d") {
		t.Errorf("Expected depfile in cc_compile rule, got: %s", output)
	}

	if !strings.Contains(output, "deps = gcc") {
		t.Errorf("Expected 'deps = gcc' in cc_compile rule, got: %s", output)
	}

	if !strings.Contains(output, "-MMD -MF $out.d") {
		t.Errorf("Expected -MMD -MF in compile command, got: %s", output)
	}
}

func TestGeneratorPhonyTargets(t *testing.T) {
	g := dag.NewGraph()

	m := &parser.Module{
		Type: "cc_library",
		Map: &parser.Map{
			Properties: []*parser.Property{
				{Name: "name", Value: &parser.String{Value: "mylib"}},
				{Name: "srcs", Value: &parser.List{Values: []parser.Expression{
					&parser.String{Value: "main.c"},
				}}},
			},
		},
	}

	rules := map[string]BuildRule{
		"cc_library": &ccLibrary{},
	}

	modules := map[string]*parser.Module{
		"mylib": m,
	}

	g.AddModule(&dagMockModule{name: "mylib"})

	gen := NewGenerator(g, rules, modules)

	var buf bytes.Buffer
	err := gen.Generate(&buf)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	output := buf.String()

	if !strings.Contains(output, "build mylib: phony libmylib.a") {
		t.Errorf("Expected phony target for mylib, got: %s", output)
	}
}

func TestWriterSubninja(t *testing.T) {
	var buf bytes.Buffer
	w := NewWriter(&buf)
	w.Subninja("path/to/other.ninja")
	output := buf.String()
	if !strings.Contains(output, "subninja path/to/other.ninja") {
		t.Errorf("Expected subninja directive, got: %s", output)
	}
}

func TestWriterInclude(t *testing.T) {
	var buf bytes.Buffer
	w := NewWriter(&buf)
	w.Include("rules.ninja")
	output := buf.String()
	if !strings.Contains(output, "include rules.ninja") {
		t.Errorf("Expected include directive, got: %s", output)
	}
}

func TestWriterPhony(t *testing.T) {
	var buf bytes.Buffer
	w := NewWriter(&buf)
	w.Phony("mylib.a", []string{"mylib.o", "helper.o"})
	output := buf.String()
	if !strings.Contains(output, "build mylib.a: phony mylib.o helper.o") {
		t.Errorf("Expected phony target, got: %s", output)
	}
}

func TestWriterDefault(t *testing.T) {
	var buf bytes.Buffer
	w := NewWriter(&buf)
	w.Default([]string{"app", "libfoo.a"})
	output := buf.String()
	if !strings.Contains(output, "default app libfoo.a") {
		t.Errorf("Expected default targets, got: %s", output)
	}
}

func TestWriterBuildWithVars(t *testing.T) {
	var buf bytes.Buffer
	w := NewWriter(&buf)
	w.BuildWithVars("out.o", "cc", []string{"in.c"}, []string{"generated.h"}, map[string]string{
		"flags": "-Wall -O2",
	})
	output := buf.String()
	if !strings.Contains(output, "build out.o: cc in.c || generated.h") {
		t.Errorf("Expected build edge with order-only deps, got: %s", output)
	}
	if !strings.Contains(output, "flags = -Wall -O2") {
		t.Errorf("Expected variable in build edge, got: %s", output)
	}
}

func TestProtoLibraryRule(t *testing.T) {
	r := &protoLibraryRule{}
	m := &parser.Module{
		Type: "proto_library",
		Map: &parser.Map{
			Properties: []*parser.Property{
				{Name: "name", Value: &parser.String{Value: "myproto"}},
				{Name: "srcs", Value: &parser.List{Values: []parser.Expression{
					&parser.String{Value: "api.proto"},
				}}},
			},
		},
	}

	outs := r.Outputs(m)
	if len(outs) != 2 || outs[0] != "api.pb.h" || outs[1] != "api.pb.cc" {
		t.Errorf("Expected [api.pb.h, api.pb.cc], got %v", outs)
	}

	edge := r.NinjaEdge(m)
	if !strings.Contains(edge, "protoc") {
		t.Errorf("Expected protoc in edge, got: %s", edge)
	}
	if !strings.Contains(edge, "api.proto") {
		t.Errorf("Expected api.proto in edge, got: %s", edge)
	}
	if !strings.Contains(edge, "out_type = cc") {
		t.Errorf("Expected out_type = cc in edge, got: %s", edge)
	}
}

func TestProtoLibraryGoOutput(t *testing.T) {
	r := &protoLibraryRule{}
	m := &parser.Module{
		Type: "proto_library",
		Map: &parser.Map{
			Properties: []*parser.Property{
				{Name: "name", Value: &parser.String{Value: "myproto"}},
				{Name: "srcs", Value: &parser.List{Values: []parser.Expression{
					&parser.String{Value: "api.proto"},
				}}},
				{Name: "out", Value: &parser.String{Value: "go"}},
			},
		},
	}

	outs := r.Outputs(m)
	if len(outs) != 1 || outs[0] != "api.pb.go" {
		t.Errorf("Expected [api.pb.go], got %v", outs)
	}
}

func TestProtoLibraryJavaOutput(t *testing.T) {
	r := &protoLibraryRule{}
	m := &parser.Module{
		Type: "proto_library",
		Map: &parser.Map{
			Properties: []*parser.Property{
				{Name: "name", Value: &parser.String{Value: "myproto"}},
				{Name: "srcs", Value: &parser.List{Values: []parser.Expression{
					&parser.String{Value: "api.proto"},
				}}},
				{Name: "out", Value: &parser.String{Value: "java"}},
			},
		},
	}

	outs := r.Outputs(m)
	if len(outs) != 1 || outs[0] != "api.java" {
		t.Errorf("Expected [api.java], got %v", outs)
	}
}

func TestProtoLibraryWithPlugins(t *testing.T) {
	r := &protoLibraryRule{}
	m := &parser.Module{
		Type: "proto_library",
		Map: &parser.Map{
			Properties: []*parser.Property{
				{Name: "name", Value: &parser.String{Value: "myproto"}},
				{Name: "srcs", Value: &parser.List{Values: []parser.Expression{
					&parser.String{Value: "api.proto"},
				}}},
				{Name: "plugins", Value: &parser.List{Values: []parser.Expression{
					&parser.String{Value: "protoc-gen-go"},
				}}},
				{Name: "proto_paths", Value: &parser.List{Values: []parser.Expression{
					&parser.String{Value: "src/proto"},
				}}},
			},
		},
	}

	edge := r.NinjaEdge(m)
	if !strings.Contains(edge, "--plugin=protoc-gen-go") {
		t.Errorf("Expected plugin flag in edge, got: %s", edge)
	}
	if !strings.Contains(edge, "--proto_path=src/proto") {
		t.Errorf("Expected proto_path in edge, got: %s", edge)
	}
}

func TestDepfileInCppRules(t *testing.T) {
	r := &cppLibrary{}
	rule := r.NinjaRule()
	if !strings.Contains(rule, "depfile = $out.d") {
		t.Errorf("Expected depfile in cpp_compile rule, got: %s", rule)
	}
	if !strings.Contains(rule, "deps = gcc") {
		t.Errorf("Expected deps = gcc in cpp_compile rule, got: %s", rule)
	}

	r2 := &cppBinary{}
	rule2 := r2.NinjaRule()
	if !strings.Contains(rule2, "depfile = $out.d") {
		t.Errorf("Expected depfile in cpp_binary compile rule, got: %s", rule2)
	}
}

func TestCCSharedLibraryIncludesSharedDeps(t *testing.T) {
	r := &ccLibrary{}
	m := &parser.Module{
		Type: "cc_library",
		Map: &parser.Map{Properties: []*parser.Property{
			{Name: "name", Value: &parser.String{Value: "app"}},
			{Name: "shared", Value: &parser.Bool{Value: true}},
			{Name: "srcs", Value: &parser.List{Values: []parser.Expression{&parser.String{Value: "app.c"}}}},
			{Name: "shared_libs", Value: &parser.List{Values: []parser.Expression{&parser.String{Value: ":base"}}}},
		}},
	}

	edge := r.NinjaEdge(m)
	if !strings.Contains(edge, "build libapp.so: cc_shared app_app.o libbase.so") {
		t.Fatalf("Expected shared library input dependency in edge, got: %s", edge)
	}
	if !strings.Contains(edge, "-lbase") {
		t.Fatalf("Expected linker flag for shared dep, got: %s", edge)
	}
}

func TestCppSharedLibraryIncludesSharedDeps(t *testing.T) {
	r := &cppLibrary{}
	m := &parser.Module{
		Type: "cpp_library",
		Map: &parser.Map{Properties: []*parser.Property{
			{Name: "name", Value: &parser.String{Value: "app"}},
			{Name: "shared", Value: &parser.Bool{Value: true}},
			{Name: "srcs", Value: &parser.List{Values: []parser.Expression{&parser.String{Value: "app.cpp"}}}},
			{Name: "shared_libs", Value: &parser.List{Values: []parser.Expression{&parser.String{Value: ":base"}}}},
		}},
	}

	edge := r.NinjaEdge(m)
	if !strings.Contains(edge, "build libapp.so: cpp_shared app_app.o libbase.so") {
		t.Fatalf("Expected shared library input dependency in edge, got: %s", edge)
	}
	if !strings.Contains(edge, "-lbase") {
		t.Fatalf("Expected linker flag for shared dep, got: %s", edge)
	}
}

func TestCCLibraryObjectOutputsAreUniqueForDuplicateBasenames(t *testing.T) {
	r := &ccLibrary{}
	m := &parser.Module{
		Type: "cc_library",
		Map: &parser.Map{Properties: []*parser.Property{
			{Name: "name", Value: &parser.String{Value: "dupes"}},
			{Name: "srcs", Value: &parser.List{Values: []parser.Expression{
				&parser.String{Value: "src/foo/util.c"},
				&parser.String{Value: "tests/foo/util.c"},
			}}},
		}},
	}

	edge := r.NinjaEdge(m)
	if !strings.Contains(edge, "build dupes_src_foo_util.o: cc_compile src/foo/util.c") {
		t.Fatalf("Expected unique object output for first source, got: %s", edge)
	}
	if !strings.Contains(edge, "build dupes_tests_foo_util.o: cc_compile tests/foo/util.c") {
		t.Fatalf("Expected unique object output for second source, got: %s", edge)
	}
	if !strings.Contains(edge, "build libdupes.a: cc_archive dupes_src_foo_util.o dupes_tests_foo_util.o") {
		t.Fatalf("Expected archive to use both unique object outputs, got: %s", edge)
	}
}

func TestCCObjectMultiSourceProducesOneOutputPerSource(t *testing.T) {
	r := &ccObject{}
	m := &parser.Module{
		Type: "cc_object",
		Map: &parser.Map{Properties: []*parser.Property{
			{Name: "name", Value: &parser.String{Value: "bundle"}},
			{Name: "srcs", Value: &parser.List{Values: []parser.Expression{
				&parser.String{Value: "src/foo.c"},
				&parser.String{Value: "src/bar.c"},
			}}},
		}},
	}

	outputs := r.Outputs(m)
	if len(outputs) != 2 || outputs[0] != "bundle_src_foo.o" || outputs[1] != "bundle_src_bar.o" {
		t.Fatalf("Expected one object output per source, got: %v", outputs)
	}

	edge := r.NinjaEdge(m)
	if !strings.Contains(edge, "build bundle_src_foo.o: cc_compile src/foo.c") {
		t.Fatalf("Expected compile edge for first source, got: %s", edge)
	}
	if !strings.Contains(edge, "build bundle_src_bar.o: cc_compile src/bar.c") {
		t.Fatalf("Expected compile edge for second source, got: %s", edge)
	}
	if strings.Contains(edge, "cc_compile src/foo.c src/bar.c") {
		t.Fatalf("Expected separate compile edges for multi-source cc_object, got: %s", edge)
	}
}

func TestGeneratorAddsIncludesFromSharedLibs(t *testing.T) {
	g := dag.NewGraph()

	base := &parser.Module{
		Type: "cc_library_shared",
		Map: &parser.Map{Properties: []*parser.Property{
			{Name: "name", Value: &parser.String{Value: "base"}},
			{Name: "srcs", Value: &parser.List{Values: []parser.Expression{
				&parser.String{Value: "base.c"},
			}}},
			{Name: "export_include_dirs", Value: &parser.List{Values: []parser.Expression{
				&parser.String{Value: "include/base"},
			}}},
			{Name: "exported_headers", Value: &parser.List{Values: []parser.Expression{
				&parser.String{Value: "generated/base/api.h"},
			}}},
		}},
	}

	app := &parser.Module{
		Type: "cc_binary",
		Map: &parser.Map{Properties: []*parser.Property{
			{Name: "name", Value: &parser.String{Value: "app"}},
			{Name: "srcs", Value: &parser.List{Values: []parser.Expression{
				&parser.String{Value: "app.c"},
			}}},
			{Name: "shared_libs", Value: &parser.List{Values: []parser.Expression{
				&parser.String{Value: ":base"},
			}}},
		}},
	}

	rules := map[string]BuildRule{
		"cc_library_shared": &ccLibraryShared{},
		"cc_binary":         &ccBinary{},
	}
	modules := map[string]*parser.Module{
		"base": base,
		"app":  app,
	}

	g.AddModule(&dagMockModule{name: "base"})
	g.AddModule(&dagMockModule{name: "app"})
	g.AddEdge("app", "base")

	gen := NewGenerator(g, rules, modules)

	var buf bytes.Buffer
	if err := gen.Generate(&buf); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	output := buf.String()
	if !strings.Contains(output, "build app_app.o: cc_compile app.c") {
		t.Fatalf("Expected app compile edge in output, got: %s", output)
	}
	if !strings.Contains(output, "-Iinclude/base") {
		t.Fatalf("Expected shared lib export include dir in output, got: %s", output)
	}
	if !strings.Contains(output, "-Igenerated/base") {
		t.Fatalf("Expected shared lib exported header dir in output, got: %s", output)
	}
}

func TestGeneratorDeduplicatesCustomRulesForSameCommand(t *testing.T) {
	g := dag.NewGraph()

	modA := &parser.Module{Type: "custom", Map: &parser.Map{Properties: []*parser.Property{
		{Name: "name", Value: &parser.String{Value: "a"}},
		{Name: "outs", Value: &parser.List{Values: []parser.Expression{&parser.String{Value: "a.out"}}}},
		{Name: "cmd", Value: &parser.String{Value: "touch $out"}},
	}}}
	modB := &parser.Module{Type: "custom", Map: &parser.Map{Properties: []*parser.Property{
		{Name: "name", Value: &parser.String{Value: "b"}},
		{Name: "outs", Value: &parser.List{Values: []parser.Expression{&parser.String{Value: "b.out"}}}},
		{Name: "cmd", Value: &parser.String{Value: "touch $out"}},
	}}}

	rules := map[string]BuildRule{"custom": &customRule{}}
	modules := map[string]*parser.Module{"a": modA, "b": modB}

	g.AddModule(&dagMockModule{name: "a"})
	g.AddModule(&dagMockModule{name: "b"})

	gen := NewGenerator(g, rules, modules)
	var buf bytes.Buffer
	if err := gen.Generate(&buf); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	output := buf.String()
	if strings.Count(output, "rule custom_command") != 1 {
		t.Fatalf("Expected one shared custom rule definition, got output: %s", output)
	}
	if strings.Count(output, "build a.out: custom_command") != 1 || strings.Count(output, "build b.out: custom_command") != 1 {
		t.Fatalf("Expected both build edges to reuse shared custom rule, got output: %s", output)
	}
	if !strings.Contains(output, " cmd = touch a.out") || !strings.Contains(output, " cmd = touch b.out") {
		t.Fatalf("Expected per-edge custom commands, got output: %s", output)
	}
}

func TestGeneratorSeparatesCustomRulesForDifferentCommands(t *testing.T) {
	g := dag.NewGraph()

	modA := &parser.Module{Type: "custom", Map: &parser.Map{Properties: []*parser.Property{
		{Name: "name", Value: &parser.String{Value: "a"}},
		{Name: "outs", Value: &parser.List{Values: []parser.Expression{&parser.String{Value: "a.out"}}}},
		{Name: "cmd", Value: &parser.String{Value: "touch $out"}},
	}}}
	modB := &parser.Module{Type: "custom", Map: &parser.Map{Properties: []*parser.Property{
		{Name: "name", Value: &parser.String{Value: "b"}},
		{Name: "outs", Value: &parser.List{Values: []parser.Expression{&parser.String{Value: "b.out"}}}},
		{Name: "cmd", Value: &parser.String{Value: "cp in out"}},
	}}}

	rules := map[string]BuildRule{"custom": &customRule{}}
	modules := map[string]*parser.Module{"a": modA, "b": modB}

	g.AddModule(&dagMockModule{name: "a"})
	g.AddModule(&dagMockModule{name: "b"})

	gen := NewGenerator(g, rules, modules)
	var buf bytes.Buffer
	if err := gen.Generate(&buf); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	output := buf.String()
	if strings.Count(output, "rule custom_command") != 1 {
		t.Fatalf("Expected one shared custom rule definition, got output: %s", output)
	}
	if !strings.Contains(output, " cmd = touch a.out") || !strings.Contains(output, " cmd = cp in out") {
		t.Fatalf("Expected distinct per-edge commands, got output: %s", output)
	}
}
