// ninja/ninja_test.go - Tests for ninja package
package ninja

import (
	"bytes"
	"strings"
	"testing"

	"minibp/dag"
	"minibp/parser"
)

// mockRule implements BuildRule for testing
type mockRule struct {
	name string
}

func (r *mockRule) Name() string {
	return r.name
}

func (r *mockRule) NinjaRule() string {
	return "rule " + r.name + "\n  command = echo " + r.name + "\n"
}

func (r *mockRule) NinjaEdge(m *parser.Module) string {
	if m == nil {
		return ""
	}
	return "build " + getName(m) + ": " + r.name + " " + formatSrcs(getSrcs(m)) + "\n"
}

func (r *mockRule) Outputs(m *parser.Module) []string {
	return []string{getName(m)}
}

func (r *mockRule) Desc(m *parser.Module, srcFile string) string {
	return "mock"
}

func TestNewWriter(t *testing.T) {
	var buf bytes.Buffer
	w := NewWriter(&buf)
	if w == nil {
		t.Fatal("NewWriter returned nil")
	}
}

func TestWriterComment(t *testing.T) {
	var buf bytes.Buffer
	w := NewWriter(&buf)
	w.Comment("Test comment")
	output := buf.String()
	if !strings.Contains(output, "# Test comment") {
		t.Errorf("Expected comment in output, got: %s", output)
	}
}

func TestWriterVariable(t *testing.T) {
	var buf bytes.Buffer
	w := NewWriter(&buf)
	w.Variable("key", "value")
	output := buf.String()
	if !strings.Contains(output, "key = value") {
		t.Errorf("Expected variable in output, got: %s", output)
	}
}

func TestWriterRule(t *testing.T) {
	var buf bytes.Buffer
	w := NewWriter(&buf)
	w.Rule("cc", "gcc -c $in -o $out")
	output := buf.String()
	if !strings.Contains(output, "rule cc") {
		t.Errorf("Expected rule cc in output, got: %s", output)
	}
	if !strings.Contains(output, "command = gcc") {
		t.Errorf("Expected command in output, got: %s", output)
	}
}

func TestWriterBuild(t *testing.T) {
	var buf bytes.Buffer
	w := NewWriter(&buf)
	w.Build("out.o", "cc", []string{"in.c"}, nil)
	output := buf.String()
	if !strings.Contains(output, "build out.o: cc in.c") {
		t.Errorf("Expected build edge in output, got: %s", output)
	}
}

func TestNewGenerator(t *testing.T) {
	g := dag.NewGraph()
	rules := make(map[string]BuildRule)
	modules := make(map[string]*parser.Module)
	gen := NewGenerator(g, rules, modules)
	if gen == nil {
		t.Fatal("NewGenerator returned nil")
	}
}

func TestGeneratorGenerate(t *testing.T) {
	g := dag.NewGraph()

	// Create a mock module
	m := &parser.Module{
		Type: "mock",
		Map: &parser.Map{
			Properties: []*parser.Property{
				{Name: "name", Value: &parser.String{Value: "hello"}},
				{Name: "srcs", Value: &parser.List{Values: []parser.Expression{
					&parser.String{Value: "main.c"},
				}}},
			},
		},
	}

	// Setup rules
	rules := map[string]BuildRule{
		"mock": &mockRule{name: "mock"},
	}

	// Setup modules
	modules := map[string]*parser.Module{
		"hello": m,
	}

	gen := NewGenerator(g, rules, modules)

	var buf bytes.Buffer
	err := gen.Generate(&buf)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	output := buf.String()

	// Check header
	if !strings.Contains(output, "Generated by minibp") {
		t.Errorf("Expected header in output, got: %s", output)
	}

	// Check rule definition
	if !strings.Contains(output, "rule mock") {
		t.Errorf("Expected rule definition in output, got: %s", output)
	}
}

func TestGeneratorWithCCLibrary(t *testing.T) {
	g := dag.NewGraph()

	// Create a cc_library module
	m := &parser.Module{
		Type: "cc_library",
		Map: &parser.Map{
			Properties: []*parser.Property{
				{Name: "name", Value: &parser.String{Value: "mylib"}},
				{Name: "srcs", Value: &parser.List{Values: []parser.Expression{
					&parser.String{Value: "lib.c"},
				}}},
			},
		},
	}

	rules := map[string]BuildRule{
		"cc_library": &ccLibrary{},
	}

	modules := map[string]*parser.Module{
		"mylib": m,
	}

	gen := NewGenerator(g, rules, modules)

	var buf bytes.Buffer
	err := gen.Generate(&buf)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	output := buf.String()

	// Check for cc_compile rule
	if !strings.Contains(output, "rule cc_compile") {
		t.Errorf("Expected cc_compile rule in output, got: %s", output)
	}

	// Check for archive rule
	if !strings.Contains(output, "rule cc_archive") {
		t.Errorf("Expected cc_archive rule in output, got: %s", output)
	}
}
